### ISSUE TITLE
Restructure tech naming in config.yaml 

### ISSUE THREAD

**Issue by trevorb1** [DeltaE/Canada-U.S.-ElecTrade#97]
In pr #96 we clarified what are fuels and what are techs in the `config.yaml` file (yay!). This highlighted a bigger problem that we are repeating fuel definitions in the configuration file, which is making tracking the flow of data hard. 

https://github.com/DeltaE/Canada-U.S.-ElecTrade/blob/a2d6e4f1380f658b164f0299deba7a83ad73d51a/scripts/config.yaml#L31-L75

Im wondering if its better to remove the `mine_fuels` and `rnw_fuels` and instead specify what technologies are renewable and consumable fuels (ie. require MIN) techs. Then we can just search through the `tech_to_fuel` dictionary to get the fuels? 

So the `master_techs` dictionary would instead look something like...

```
PWR: 
    MIN: 
       - 'URN' # Nuclear 
       - 'CCG' # Gas Combined Cycle  
       - 'CTG' # Gas Combustion Turbine 
       - 'COA' # Coal 
       - 'COC' # Coal CCS 
    RNW: 
       - 'HYD' # Hydro  
       - 'SPV' # Solar 
       - 'WND' # Wind
       - 'BIO' # Biomass 
```

This may also simplify the the `techDataFrame( ... )` function as well (so we arnt mixing techs and fuels quite as much)
